name: DeadSouls
version: 1.0-mc1.13.2
api-version: 1.13
main: com.darkyen.minecraft.DeadSouls
authors: [Darkyen]
commands:
  dead_souls_free_soul:
    description: (Internal command) Allow anyone to reclaim items held by the soul.
    usage: /dead_souls_free_soul <soul id>
    permission: com.darkyen.minecraft.deadsouls.hassoul
permissions:
  com.darkyen.minecraft.deadsouls.hassoul:
    description: Has soul that holds onto their items.
    default: true